version: '3' 

services: 

  training:
    build:
      context: https://github.com/docker-hy/ml-kurkkumopo-training.git
    container_name: training
 
    volumes: 
      - files:/src/model
      - files2:/src/imgs



  frontend:
    build:
      context: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
    container_name: frontend
    
    ports: 
      - 3000:3000


  backend:
    build:
      context: https://github.com/docker-hy/ml-kurkkumopo-backend.git
    container_name: backend

    volumes: 
      - files:/src/model
    ports: 
      - 5000:5000
   

volumes:
  files:
  files2:
        
        
