version: '3' 

services: 

   db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: example



    
   munappi: 
    image: munappi
    environment:
        -  API_URL=http://localhost/api

        
   munbakki:
     image: munbakki
     volumes: 
       - ./logs.txt:/backend-example-docker/logs.txt 

     environment:
        - FRONT_URL=http://localhost
        - REDIS=redis
        - REDIS_PORT=6379
        - DB_USERNAME=docker
        - DB_PASSWORD=example
        - DB_HOST=db    


   redis:
     image: "redis:alpine" 
     
     
   nginx: 
     image: nginx
     volumes: 
       - ./nginx.conf:/etc/nginx/nginx.conf  
     ports: 
        - 80:80
        
     restart: unless-stopped

     depends_on:
       - munappi
       - munbakki



        
        
